name: Test

on:
    push:
    pull_request:
        types: [opened, synchronize, edited, reopened]

jobs:
    test:
        name: PHP ${{ matrix.php-version }} ${{ matrix.description || '' }}
        runs-on: ubuntu-latest
        continue-on-error: false
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'
                    - '8.5'
                symfony-version: [false]
                composer-install-flags: [false]
                minimum-stability: ['stable']
                include:
                    - php-version: '8.1'
                      symfony-version: '5.4.*'
                      description: 'Symfony 5.4 LTS'
                    - php-version: '8.1'
                      symfony-version: '6.4.*'
                      description: 'Symfony 6.4 LTS'
                    - php-version: '8.2'
                      symfony-version: '7.4.*'
                      description: 'Symfony 7.4 LTS'
                    - php-version: '8.5'
                      minimum-stability: 'dev'
                      description: 'dev'
                    - php-version: '8.1'
                      composer-install-flags: '--prefer-lowest --prefer-stable'
                      description: 'lowest'
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  ini-values: "memory_limit=-1"
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2, flex

            - name: Validate composer.json
              run: composer validate --no-check-lock

            - name: Configure minimum-stability
              run: composer config minimum-stability ${{ matrix.minimum-stability }}

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress ${{ matrix.composer-install-flags || '' }}
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony-version || '' }}

            - name: PHPSpec
              run: vendor/bin/phpspec run -f pretty

            - name: Behat
              run: vendor/bin/behat -fprogress --strict
