name: Test

on:
    push:
    pull_request:
        types: [opened, synchronize, edited, reopened]

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + Symfony ${{ matrix.symfony-version }}
        runs-on: ubuntu-latest
        continue-on-error: false
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'
                    - '8.5'
                symfony-version:
                    - 'none'
                include:
                    - php-version: '8.1'
                      symfony-version: '5.4.*'
                    - php-version: '8.1'
                      symfony-version: '6.4.*'
                    - php-version: '8.2'
                      symfony-version: '7.4.*'
                    - php-version: '8.5'
                      symfony-version: 'dev'
                      minimum-stability: 'dev'
                    - php-version: '8.1'
                      symfony-version: 'lowest'
                      composer-install-flags: '--prefer-lowest --prefer-stable'
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  ini-values: "memory_limit=-1"
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2, flex

            - name: Validate composer.json
              run: composer validate --no-check-lock

            - name: Allow dev dependencies
              run: composer config minimum-stability dev
              if: matrix.minimum-stability == 'dev'

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress ${{ matrix.composer-install-flags }}
              env:
                  SYMFONY_REQUIRE: ${{ (matrix.symfony-version != 'none' && matrix.symfony-version != 'dev' && matrix.symfony-version != 'lowest') && matrix.symfony-version || '' }}

            - name: PHPSpec
              run: vendor/bin/phpspec run -f pretty

            - name: Behat
              run: vendor/bin/behat -fprogress --strict
